spring:
  datasource:
    url: jdbc:mysql://localhost:3306/concert
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
#    hibernate:
#      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: my-group


logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace

payment.topic: paymentTopic